let characterSprites = {}
let projectileSprites = {}
let particleSprites = {}
let collisionSprites = {}
let stageBackgrounds = {}
let meters = {}
let menuImages = {}
let bananaFont = {}
let bananaCursor = {}
let softStart = {}
let startButton = {}
let characterSelection = {}
let p1selection = {}
let p2selection = {}
let p1back = {}
let p2back = {}
let portraits = {}
let gradient = {}

function preload() {
	menuImages["brawl"] = loadImage('menuImages/brawl.png');
	menuImages["jungle"] = loadImage('menuImages/jungle.png');
	menuImages["jungle2"] = loadImage('menuImages/jungle2.png');
	menuImages["bananabeach"] = loadImage('menuImages/bananabeach.png');
	menuImages["coming soon"] = loadImage('menuImages/working.png');
	menuImages["controls"] = loadImage('menuImages/controls.png');
	menuImages["options"] = loadImage('menuImages/controls.png');
	menuImages["p1"] = loadImage('menuImages/controls.png');
	menuImages["p2"] = loadImage('menuImages/controls.png');
	menuImages["exit"] = loadImage('menuImages/back.png');
	menuImages["back"] = loadImage('menuImages/back.png');
	menuImages["quit"] = loadImage('menuImages/back.png');
	menuImages["training"] = loadImage('menuImages/training.png');
	menuImages["start"] = loadImage('menuImages/start.png');

	portraits["banannon"] = loadImage('portraits/banannon.png');
	portraits["bananagent"] = loadImage('portraits/bananagent.png');
	portraits["bananimal"] = loadImage('portraits/bananimal.png');
	portraits["snow"] = loadImage('portraits/snow.png');
	portraits["demonana"] = loadImage('portraits/demonana.png');
	portraits["bllna"] = loadImage('portraits/bllna.png');

	collisionSprites["rock"] = loadImage('collision/rock.png');
	collisionSprites["wood"] = loadImage('collision/wood.png');
	stageBackgrounds["jungle"] = loadImage('stageBackgrounds/jungle.png');
	stageBackgrounds["jungle2"] = loadImage('stageBackgrounds/jungle2.png');
	stageBackgrounds["bananabeach"] = loadImage('stageBackgrounds/bananaBeach.png');
	
	meters["banannon"] = loadImage('meters/banannon.png');
	meters["bananagent"] = loadImage('meters/bananagent.png');
	meters["snow"] = loadImage('meters/snow.png');
	meters["demonana"] = loadImage('meters/demonana.png');
	meters["bananimal"] = loadImage('meters/bananimal.png');

	characterSprites["banannon"] = loadImage('characterSprites/banannonSprites.png');
	characterSprites["bananagent"] = loadImage('characterSprites/bananagentSprites.png');
	characterSprites["bananinja"] = loadImage('characterSprites/bananinjaSprites.png');
	characterSprites["bllna"] = loadImage('characterSprites/bllnaSprites.png');
	characterSprites["bananimal"] = loadImage('characterSprites/bananimalSprites.png');
	characterSprites["demonana"] = loadImage('characterSprites/demonanaSprites.png');
	characterSprites["snow"] = loadImage('characterSprites/snowSprites.png');

	projectileSprites["banannonball"] = loadImage('projectiles/banannonball.png');
	projectileSprites["IBM"] = loadImage('projectiles/IBM.png');
	projectileSprites["darkDart"] = loadImage('projectiles/darkDart.png');
	projectileSprites["bazooka"] = loadImage('projectiles/bazooka.png');
	projectileSprites["waterMissile"] = loadImage('projectiles/waterMissile.png');
	projectileSprites["iceSpear"] = loadImage('projectiles/iceSpear.png');
	projectileSprites["iceSpike"] = loadImage('projectiles/iceSpike.png');
	projectileSprites["iceImpale"] = loadImage('projectiles/iceImpale.png');
	projectileSprites["snowball"] = loadImage('projectiles/snowball.png');
	projectileSprites["snowPile"] = loadImage('projectiles/snowPile.png');

	particleSprites["bananaparticle_small"] = loadImage('particles/bananaparticle_small.png');
	particleSprites["bananaparticle_large"] = loadImage('particles/bananaparticle_large.png');
	particleSprites["peel"] = loadImage('particles/peel.png');
	particleSprites["run"] = loadImage('particles/run.png');
	particleSprites["doubleJump"] = loadImage('particles/doubleJump.png');
	particleSprites["banannonfire"] = loadImage('particles/banannonfire.png');
	particleSprites["banannonexplosion"] = loadImage('particles/banannonexplosion.png');
	particleSprites["questGuide"] = loadImage('particles/questGuide.png');
	particleSprites["evilSpire"] = loadImage('particles/evilSpire.png');
	particleSprites["shadowCrunch"] = loadImage('particles/shadowCrunch.png');
	particleSprites["darkWhip"] = loadImage('particles/darkWhip.png');
	particleSprites["darkCloud"] = loadImage('particles/darkCloud.png');
	particleSprites["shadowHand"] = loadImage('particles/shadowHand.png');
	particleSprites["waterBubble"] = loadImage('particles/waterBubble.png');
	particleSprites["waterExhaust"] = loadImage('particles/waterExhaust.png');
	particleSprites["waterWave"] = loadImage('particles/waterWave.png');
	particleSprites["waterSlice"] = loadImage('particles/waterSlice.png');
	particleSprites["demonWings"] = loadImage('particles/demonWings.png');
	particleSprites["demonEnergy"] = loadImage('particles/demonEnergy.png');
	particleSprites["demonFlare"] = loadImage('particles/demonFlare.png');
	particleSprites["iceSpear"] = loadImage('particles/iceSpear.png');
	particleSprites["iceScythe"] = loadImage('particles/iceScythe.png');
	particleSprites["iceHammer"] = loadImage('particles/iceHammer.png');
	particleSprites["iceSpike"] = loadImage('particles/iceSpike.png');
	particleSprites["iceShine"] = loadImage('particles/iceShine.png');
	particleSprites["iceCannon"] = loadImage('particles/iceCannon.png');
	particleSprites["iceImpale_front"] = loadImage('particles/iceImpale_front.png');
	particleSprites["iceImpale_back"] = loadImage('particles/iceImpale_back.png');
	particleSprites["iceShard_small"] = loadImage('particles/iceShard_small.png');
	particleSprites["iceShard_medium"] = loadImage('particles/iceShard_medium.png');
	particleSprites["iceShard_large"] = loadImage('particles/iceShard_large.png');
	particleSprites["snowflake_small"] = loadImage('particles/snowflake_small.png');
	particleSprites["snowflake_large"] = loadImage('particles/snowflake_large.png');
	particleSprites["glowEyes"] = loadImage('particles/glowEyes.png');

	bananaFont = loadImage('misc/bananaFont.png');
	bananaCursor = loadImage('misc/bananaCursor.png');
	softStart = loadImage('misc/softStart.png');
	startButton = loadImage('misc/startButton.png');
	characterSelection = loadImage('misc/characterSelection.png');
	p1selection = loadImage('misc/p1selection.png');
	p2selection = loadImage('misc/p2selection.png');
	p1back = loadImage('misc/p1back.png');
	p2back = loadImage('misc/p2back.png');
	gradient = loadImage('misc/gradient.png');
}