let characterSprites = {}
let projectileSprites = {}
let particleSprites = {}
let collisionSprites = {}
let stageBackgrounds = {}
let meters = {}
let menuImages = {}
let bananaFont = {}
let bananaCursor = {}
let softStart = {}
let startButton = {}
let characterSelection = {}
let p1selection = {}
let p2selection = {}
let p1back = {}
let p2back = {}
let portraits = {}
let gradient = {}

function preload() {
	menuImages["brawl"] = loadImage('images/menuImages/brawl.png');
	menuImages["jungle"] = loadImage('images/menuImages/jungle.png');
	menuImages["jungle2"] = loadImage('images/menuImages/jungle2.png');
	menuImages["bananabeach"] = loadImage('images/menuImages/bananabeach.png');
	menuImages["coming soon"] = loadImage('images/menuImages/working.png');
	menuImages["controls"] = loadImage('images/menuImages/controls.png');
	menuImages["options"] = loadImage('images/menuImages/controls.png');
	menuImages["p1"] = loadImage('images/menuImages/controls.png');
	menuImages["p2"] = loadImage('images/menuImages/controls.png');
	menuImages["exit"] = loadImage('images/menuImages/back.png');
	menuImages["back"] = loadImage('images/menuImages/back.png');
	menuImages["quit"] = loadImage('images/menuImages/back.png');
	menuImages["training"] = loadImage('images/menuImages/training.png');
	menuImages["start"] = loadImage('images/menuImages/start.png');

	portraits["banannon"] = loadImage('images/portraits/banannon.png');
	portraits["bananagent"] = loadImage('images/portraits/bananagent.png');
	portraits["bananimal"] = loadImage('images/portraits/bananimal.png');
	portraits["snow"] = loadImage('images/portraits/snow.png');
	portraits["demonana"] = loadImage('images/portraits/demonana.png');
	portraits["bllna"] = loadImage('images/portraits/bllna.png');

	collisionSprites["rock"] = loadImage('images/collision/rock.png');
	collisionSprites["wood"] = loadImage('images/collision/wood.png');
	stageBackgrounds["jungle"] = loadImage('images/stageBackgrounds/jungle.png');
	stageBackgrounds["jungle2"] = loadImage('images/stageBackgrounds/jungle2.png');
	stageBackgrounds["bananabeach"] = loadImage('images/stageBackgrounds/bananaBeach.png');
	
	meters["banannon"] = loadImage('images/meters/banannon.png');
	meters["bananagent"] = loadImage('images/meters/bananagent.png');
	meters["snow"] = loadImage('images/meters/snow.png');
	meters["demonana"] = loadImage('images/meters/demonana.png');
	meters["bananimal"] = loadImage('images/meters/bananimal.png');

	characterSprites["banannon"] = loadImage('images/characterSprites/banannonSprites.png');
	characterSprites["bananagent"] = loadImage('images/characterSprites/bananagentSprites.png');
	characterSprites["bananinja"] = loadImage('images/characterSprites/bananinjaSprites.png');
	characterSprites["bllna"] = loadImage('images/characterSprites/bllnaSprites.png');
	characterSprites["bananimal"] = loadImage('images/characterSprites/bananimalSprites.png');
	characterSprites["demonana"] = loadImage('images/characterSprites/demonanaSprites.png');
	characterSprites["snow"] = loadImage('images/characterSprites/snowSprites.png');

	projectileSprites["banannonball"] = loadImage('images/projectiles/banannonball.png');
	projectileSprites["IBM"] = loadImage('images/projectiles/IBM.png');
	projectileSprites["darkDart"] = loadImage('images/projectiles/darkDart.png');
	projectileSprites["bazooka"] = loadImage('images/projectiles/bazooka.png');
	projectileSprites["waterMissile"] = loadImage('images/projectiles/waterMissile.png');
	projectileSprites["iceSpear"] = loadImage('images/projectiles/iceSpear.png');
	projectileSprites["iceSpike"] = loadImage('images/projectiles/iceSpike.png');
	projectileSprites["iceImpale"] = loadImage('images/projectiles/iceImpale.png');
	projectileSprites["snowball"] = loadImage('images/projectiles/snowball.png');
	projectileSprites["snowPile"] = loadImage('images/projectiles/snowPile.png');

	particleSprites["bananaparticle_small"] = loadImage('images/particles/bananaparticle_small.png');
	particleSprites["bananaparticle_large"] = loadImage('images/particles/bananaparticle_large.png');
	particleSprites["peel"] = loadImage('images/particles/peel.png');
	particleSprites["run"] = loadImage('images/particles/run.png');
	particleSprites["doubleJump"] = loadImage('images/particles/doubleJump.png');
	particleSprites["banannonfire"] = loadImage('images/particles/banannonfire.png');
	particleSprites["banannonexplosion"] = loadImage('images/particles/banannonexplosion.png');
	particleSprites["questGuide"] = loadImage('images/particles/questGuide.png');
	particleSprites["evilSpire"] = loadImage('images/particles/evilSpire.png');
	particleSprites["shadowCrunch"] = loadImage('images/particles/shadowCrunch.png');
	particleSprites["darkWhip"] = loadImage('images/particles/darkWhip.png');
	particleSprites["darkCloud"] = loadImage('images/particles/darkCloud.png');
	particleSprites["shadowHand"] = loadImage('images/particles/shadowHand.png');
	particleSprites["waterBubble"] = loadImage('images/particles/waterBubble.png');
	particleSprites["waterExhaust"] = loadImage('images/particles/waterExhaust.png');
	particleSprites["waterWave"] = loadImage('images/particles/waterWave.png');
	particleSprites["waterSlice"] = loadImage('images/particles/waterSlice.png');
	particleSprites["demonWings"] = loadImage('images/particles/demonWings.png');
	particleSprites["demonEnergy"] = loadImage('images/particles/demonEnergy.png');
	particleSprites["demonFlare"] = loadImage('images/particles/demonFlare.png');
	particleSprites["iceSpear"] = loadImage('images/particles/iceSpear.png');
	particleSprites["iceScythe"] = loadImage('images/particles/iceScythe.png');
	particleSprites["iceHammer"] = loadImage('images/particles/iceHammer.png');
	particleSprites["iceSpike"] = loadImage('images/particles/iceSpike.png');
	particleSprites["iceShine"] = loadImage('images/particles/iceShine.png');
	particleSprites["iceCannon"] = loadImage('images/particles/iceCannon.png');
	particleSprites["iceImpale_front"] = loadImage('images/particles/iceImpale_front.png');
	particleSprites["iceImpale_back"] = loadImage('images/particles/iceImpale_back.png');
	particleSprites["iceShard_small"] = loadImage('images/particles/iceShard_small.png');
	particleSprites["iceShard_medium"] = loadImage('images/particles/iceShard_medium.png');
	particleSprites["iceShard_large"] = loadImage('images/particles/iceShard_large.png');
	particleSprites["snowflake_small"] = loadImage('images/particles/snowflake_small.png');
	particleSprites["snowflake_large"] = loadImage('images/particles/snowflake_large.png');
	particleSprites["glowEyes"] = loadImage('images/particles/glowEyes.png');

	bananaFont = loadImage('images/misc/bananaFont.png');
	bananaCursor = loadImage('images/misc/bananaCursor.png');
	softStart = loadImage('images/misc/softStart.png');
	startButton = loadImage('images/misc/startButton.png');
	characterSelection = loadImage('images/misc/characterSelection.png');
	p1selection = loadImage('images/misc/p1selection.png');
	p2selection = loadImage('images/misc/p2selection.png');
	p1back = loadImage('images/misc/p1back.png');
	p2back = loadImage('images/misc/p2back.png');
	gradient = loadImage('images/misc/gradient.png');
}